### ISSUE TITLE
ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's%'

### ISSUE THREAD

**Issue by longhorn09** [longhorn09/lorebot#10]
```
 25 2017-07-05 02:21:52 : patrick                        !stat harn's
 26 { Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's%'
    ' at line 1
 27     at Query.Sequence._packetToError (/home/ntang/lorebot/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
 28     at Query.ErrorPacket (/home/ntang/lorebot/node_modules/mysql/lib/protocol/sequences/Query.js:77:18)
 29     at Protocol._parsePacket (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:280:23)
 30     at Parser.write (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Parser.js:75:12)
 31     at Protocol.write (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
 32     at Socket.<anonymous> (/home/ntang/lorebot/node_modules/mysql/lib/Connection.js:103:28)
 33     at emitOne (events.js:96:13)
 34     at Socket.emit (events.js:191:7)
 35     at readableAddChunk (_stream_readable.js:178:18)
 36     at Socket.Readable.push (_stream_readable.js:136:10)
 37     --------------------
 38     at Protocol._enqueue (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:141:48)
 39     at PoolConnection.query (/home/ntang/lorebot/node_modules/mysql/lib/Connection.js:208:25)
 40     at pool.getConnection (/home/ntang/lorebot/lorebot.js:658:16)
 41     at Ping.onOperationComplete [as _callback] (/home/ntang/lorebot/node_modules/mysql/lib/Pool.js:110:5)
 42     at Ping.Sequence.end (/home/ntang/lorebot/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
 43     at Ping.Sequence.OkPacket (/home/ntang/lorebot/node_modules/mysql/lib/protocol/sequences/Sequence.js:95:8)
 44     at Protocol._parsePacket (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:280:23)
 45     at Parser.write (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Parser.js:75:12)
 46     at Protocol.write (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
 47     at Socket.<anonymous> (/home/ntang/lorebot/node_modules/mysql/lib/Connection.js:103:28)
```

**Comment by longhorn09** [comment]
fixed in ProcessStat()

```whereClause += ` and Lore.OBJECT_NAME LIKE '%${mysql.escape(splitArr[i]).substring(1,mysql.escape(splitArr[i]).length-1)}%' `    ```

**Comment by longhorn09** [comment]
commit f3f9db7
