### ISSUE TITLE
Invalid Form Body content: Must be 2000 or fewer in length.

### ISSUE THREAD

**Issue by longhorn09** [longhorn09/lorebot#22]
```
1088 2019-03-03 23:43:24 : Alejandro                      !brief arm
1089 (node:6166) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
1090 content: Must be 2000 or fewer in length.
1091     at item.request.gen.end (/home/ntang/lorebot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential.js:71:65)
1092     at then (/home/ntang/lorebot/node_modules/snekfetch/src/index.js:215:21)
1093     at <anonymous>
1094     at process._tickCallback (internal/process/next_tick.js:160:7)
1095 (node:6166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async funn     ction without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

                                                                                                                             1094,5        93%
1094     at process._tickCallback (internal/process/next_tick.js:160:7)
1095 (node:6166) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async func
     tion without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
1096 2019-03-03 23:44:27 : Alejandro                      !stat troll.hide
```

**Comment by longhorn09** [comment]
```
2272 2019-03-17 01:54:20 : pastawhee                      !brief arm
2273 (node:27615) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
2274 content: Must be 2000 or fewer in length.
2275     at item.request.gen.end (/home/ntang/lorebot/node_modules/discord.js/src/client/rest/RequestHandlers/Sequential     .js:71:65)
2276     at then (/home/ntang/lorebot/node_modules/snekfetch/src/index.js:215:21)
2277     at <anonymous>
2278     at process._tickCallback (internal/process/next_tick.js:160:7)
2279 (node:27615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwin     g inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().      (rejection id: 2)
2280 (node:27615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise reje     ctions that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by longhorn09** [comment]
```
slav                           !brief ancient
(node:1379) UnhandledPromiseRejectionWarning: DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
```

**Comment by longhorn09** [comment]
Also occurs with ```!query affects=resist_acid```
