### ISSUE TITLE
Issue due to damage being varchar(7) field

### ISSUE THREAD

**Issue by longhorn09** [longhorn09/lorebot#23]
`  27 2019-03-07 10:05:00 : tovbard                        !stat nobleman's.ring
"MKim.log" 1546L, 114869C
                                                                                                      1,1           Top
1522     at Socket.<anonymous> (/home/ntang/lorebot/node_modules/mysql/lib/Connection.js:103:28)
1523     at Socket.emit (events.js:160:13)
1524     at addChunk (_stream_readable.js:269:12)
1525     at readableAddChunk (_stream_readable.js:256:11)
1526     at Socket.Readable.push (_stream_readable.js:213:10)
1527     --------------------
1528     at Protocol._enqueue (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:145:48)
1529     at PoolConnection.query (/home/ntang/lorebot/node_modules/mysql/lib/Connection.js:208:25)
1530     at CreateUpdateLore.pool.getConnection (/home/ntang/lorebot/lorebot.js:533:16)
1531     at Ping.onOperationComplete [as _callback] (/home/ntang/lorebot/node_modules/mysql/lib/Pool.js:110:5)
1532     at Ping.Sequence.end (/home/ntang/lorebot/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
1533     at Ping.Sequence.OkPacket (/home/ntang/lorebot/node_modules/mysql/lib/protocol/sequences/Sequence.js:97:8)
1534     at Protocol._parsePacket (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:279:23)
1535     at Parser.write (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Parser.js:76:12)
1536     at Protocol.write (/home/ntang/lorebot/node_modules/mysql/lib/protocol/Protocol.js:39:16)
1537     at Socket.<anonymous> (/home/ntang/lorebot/node_modules/mysql/lib/Connection.js:103:28)
1538   code: 'ER_DATA_TOO_LONG',
1539   errno: 1406,
1540   sqlMessage: 'Data too long for column \'damage\' at row 1',
1541   sqlState: '22001',
1542   index: 0,
1543   sql: 'call CreateLore(\'shield tribal decorative wooden\',\'WEAPON\',null,\'normstorm\',\'skill charge        by      +5,ARMOR         by -10\',null,\'NOTHIEF NOPALADIN NODRUID NOCLERIC NORANGER NOWARRIOR NOBLACK_ROBE NORED_ROBE NOWH     ITE_ROBE NOS\',\'club\',\'wood\',\'ironwood\',\'1000\',null,null,null,8,null,null,null,null,null,null,null,\'variab     le\')' }
1544 2019-03-14 05:50:15 : normstorm                      !stat shield.tribal`

**Comment by longhorn09** [comment]
example lore:
```
Object 'shield tribal decorative wooden'
 Item Type: WEAPON
 Mat Class: wood         Material: ironwood
 Weight   : 8            Value   : 1000

 Affects  : skill charge        by +5
 Affects  : ARMOR         by -10
 Restricts: NOTHIEF NOPALADIN NODRUID NOCLERIC NORANGER NOWARRIOR NOBLACK_ROBE NORED_ROBE NOWHITE_ROBE NOS
HAMAN NODARK_KNIGHT
 Class    : club
 Damage   : variable

 This shield once belonged to King Phoenix and was used in many battles. He
 was often seen using it as a weapon, smashing in foes heads with a swift
 arc of his shield.
```

**Comment by longhorn09** [comment]
`ALTER TABLE Lore MODIFY COLUMN DAMAGE VARCHAR(8);`

[Link](https://stackoverflow.com/questions/22668024/how-to-change-column-size-of-varchar-type-in-mysql?rq=1)

Need to also add some error handling / truncating in the lorebot.js file

**Comment by longhorn09** [comment]
It is case sensitive, leave column name as DAMAGE.

`ALTER TABLE Lore CHANGE damage DAMAGE varchar(8);`
