### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by longhorn09** [longhorn09/lorebot#9]
```
2017-07-04 23:36:46 : patrick                        !stat towering.shield
  5 /home/ntang/lorebot/lorebot.js:48
  6   objName = match[1];
  7                  ^
  8
  9 TypeError: Cannot read property '1' of null
 10     at parseLore (/home/ntang/lorebot/lorebot.js:48:18)
 11     at Client.client.on (/home/ntang/lorebot/lorebot.js:1390:9)
 12     at emitOne (events.js:96:13)
 13     at Client.emit (events.js:191:7)
 14     at MessageCreateHandler.handle (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
 15     at WebSocketPacketManager.handle (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:102:65)
 16     at WebSocketConnection.onPacket (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:325:35)
 17     at WebSocketConnection.onMessage (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:288:17)
 18     at WebSocket.onMessage (/home/ntang/lorebot/node_modules/ws/lib/EventTarget.js:103:16)
 19     at emitTwo (events.js:106:13)
```

**Comment by longhorn09** [comment]
in parseLore, suspect perhaps the global flag 'g' is causing issue
`match = (/^Object\s'(.+)'$/g).exec(pLore.trim().split("\n")[0].trim());`

**Comment by longhorn09** [comment]
added some console.log() to help debugging in commit 37c4876

**Comment by longhorn09** [comment]
```137 2017-07-10 22:48:55 : Qwarlord                       !stat moon.staff
138 in parseLore(): pLore: Object 'use orb 'identify' orb
139 You feel informed:, pLore[0]: Object 'use orb 'identify' orb
140 /home/ntang/lorebot/lorebot.js:49
141   objName = match[1];
142                  ^
143
144 TypeError: Cannot read property '1' of null
145     at parseLore (/home/ntang/lorebot/lorebot.js:49:18)
146     at Client.client.on (/home/ntang/lorebot/lorebot.js:1472:9)
147     at emitOne (events.js:96:13)
148     at Client.emit (events.js:191:7)
149     at MessageCreateHandler.handle (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
150     at WebSocketPacketManager.handle (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:102:65)
151     at WebSocketConnection.onPacket (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:325:35)
152     at WebSocketConnection.onMessage (/home/ntang/lorebot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:288:17)
153     at WebSocket.onMessage (/home/ntang/lorebot/node_modules/ws/lib/EventTarget.js:103:16)
154     at emitTwo (events.js:106:13)
155     at WebSocket.emit (events.js:194:7)
156 error: Forever detected script exited with code: 1
157 error: Script restart attempt #2
158 Lorebot ready!```

**Comment by longhorn09** [comment]
```
Goody Bannon - Yesterday at 11:50 PM
use orb 'identify' orb
You feel informed:
 Object 'orb dragon'
 Item Type: OTHER
 Mat Class: crystal      Material: crystal
 Weight   : 3            Value   : 5000

Sharp spikes of pain rack your head.
You fall to the ground stunned!
You should know better than try to lore a fabled dragon orb.
You cannot discern anything else.
You look deep within the orb and order it to do your bidding. Suddenly, a
flash is emitted from within the orb.```

**Comment by longhorn09** [comment]
Issue is in the building of cleanArr[i] ~line 1470

**Comment by longhorn09** [comment]
commit 72d4972
